package com.k44.stn.common.error;

public enum ErrorCode {
    VALIDATION_ERROR,

    UNAUTHORIZED,
    INVALID_CREDENTIALS,

    ACCOUNT_BLOCKED,
    ACCOUNT_DELETED,

    FORBIDDEN,

    USER_NOT_FOUND,
    SQUAD_NOT_FOUND,
    COMPANY_NOT_FOUND,
    MARKER_NOT_FOUND,
    ORDER_NOT_FOUND,

    CONFLICT,
    ALREADY_IN_SQUAD,
    USER_ALREADY_EXISTS,

    INTERNAL_ERROR
}
