spring:
  application:
    name: stn
  datasource:
    url: jdbc:postgresql://localhost:5432/tactical
    username: tactical
    password: tactical
  jpa:
    open-in-view: false
  flyway:
    enabled: true
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2s
      database: 0
app:
  jwt:
    secret: "t6LCG0TgRjdvbynQggTHyWwpEiWtcRNpA4tlXUJQcd1"
    ttl: PT24H
  env: dev