-- =====================================================================
-- Flyway migration: V1__init_schema.sql
-- DB: PostgreSQL
-- Project: STN
-- =====================================================================
--
-- Generated from the STN logical schema document.
-- Notes:
-- 1) This migration creates the base schema: users, squads, companies, tactical markers, orders, geo history.
-- 2) ENUM values below are reasonable defaults; if your application already defines a stricter set,
--    align these values to match your JPA enums (or switch columns to VARCHAR/TEXT + application-level validation).

-- -----------------------
-- 1) Enum types
-- -----------------------

CREATE TYPE user_system_role AS ENUM (
    'USER',
    'ADMIN',
    'MODERATOR'
);

CREATE TYPE user_account_status AS ENUM (
    'ACTIVE',
    'BLOCKED',
    'DELETED'
);

CREATE TYPE user_status AS ENUM (
    'ALIVE',
    'DEAD'
);

CREATE TYPE order_status AS ENUM (
    'ACTIVE',
    'COMPLETED',
    'CANCELLED'
);

-- Optional enums for tactical marker type constraints.
CREATE TYPE marker_role_restriction AS ENUM (
    'ANY',
    'COMMANDER',
    'ADMIN',
    'MODERATOR'
);

CREATE TYPE marker_uniqueness_policy AS ENUM (
    'NONE',
    'SQUAD_UNIQUE',
    'COMPANY_UNIQUE',
    'GLOBAL_UNIQUE'
);

-- -----------------------
-- 2) Tables
-- -----------------------

-- avatar_icons: reference list of allowed avatars
CREATE TABLE avatar_icons (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key         VARCHAR(64)  NOT NULL,
    label       VARCHAR(255),
    image_url   TEXT,
    active      BOOLEAN      NOT NULL DEFAULT TRUE,

    CONSTRAINT uq_avatar_icons_key UNIQUE (key)
);

-- companies: top-level units
CREATE TABLE companies (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    description TEXT,
    is_open     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_companies_is_open ON companies (is_open);

-- users: accounts
-- NOTE: squad_id FK is added later to avoid circular dependency with squads(commander_id -> users)
CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(320)       NOT NULL,
    password_hash VARCHAR(255),
    nickname      VARCHAR(64),
    system_role   user_system_role   NOT NULL DEFAULT 'USER',
    account_status user_account_status NOT NULL DEFAULT 'ACTIVE',
    status        user_status        NOT NULL DEFAULT 'ALIVE',
    avatar_icon   VARCHAR(64)        NOT NULL,
    created_at    TIMESTAMPTZ        NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ        NOT NULL DEFAULT now(),

    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT fk_users_avatar_icon
        FOREIGN KEY (avatar_icon) REFERENCES avatar_icons (key)
        ON DELETE RESTRICT);

-- squads: squads with an обязательный commander (users.id) and optional company
CREATE TABLE squads (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    description  TEXT,
    is_open      BOOLEAN      NOT NULL DEFAULT TRUE,
    color        VARCHAR(16)  NOT NULL,
    company_id   BIGINT,
    commander_id BIGINT       NOT NULL,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT fk_squads_company
        FOREIGN KEY (company_id) REFERENCES companies (id)
        ON DELETE SET NULL,

    CONSTRAINT fk_squads_commander
        FOREIGN KEY (commander_id) REFERENCES users (id)
        ON DELETE RESTRICT
);

-- Add users.squad_id after squads exists
ALTER TABLE users
    ADD COLUMN squad_id BIGINT;

ALTER TABLE users
    ADD CONSTRAINT fk_users_squad
        FOREIGN KEY (squad_id) REFERENCES squads (id)
        ON DELETE SET NULL;

-- tactical_marker_types: dictionary of marker types and constraints
CREATE TABLE tactical_marker_types (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key                       VARCHAR(64)              NOT NULL,
    name                      VARCHAR(255)             NOT NULL,
    default_description       TEXT,
    icon                      TEXT,
    default_lifetime_seconds  INTEGER,
    role_restriction          marker_role_restriction  NOT NULL,
    can_send_to_company       BOOLEAN                  NOT NULL DEFAULT FALSE,
    uniqueness_policy         marker_uniqueness_policy NOT NULL DEFAULT 'NONE',
    category                  VARCHAR(128),
    active                    BOOLEAN                  NOT NULL DEFAULT TRUE,

    CONSTRAINT uq_tactical_marker_types_key UNIQUE (key)
);

CREATE INDEX idx_tactical_marker_types_active ON tactical_marker_types (active);

-- orders: squad orders
CREATE TABLE orders (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    squad_id     BIGINT       NOT NULL,
    author_id    BIGINT,
    description  TEXT         NOT NULL,
    status       order_status NOT NULL DEFAULT 'ACTIVE',
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    completed_at TIMESTAMPTZ,

    CONSTRAINT fk_orders_squad
        FOREIGN KEY (squad_id) REFERENCES squads (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_orders_author
        FOREIGN KEY (author_id) REFERENCES users (id)
        ON DELETE SET NULL
);

-- tactical_markers: markers placed on the map
CREATE TABLE tactical_markers (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    marker_type_id BIGINT      NOT NULL,
    squad_id       BIGINT      NOT NULL,
    company_id     BIGINT,
    author_id      BIGINT,
    lat            DOUBLE PRECISION NOT NULL,
    lng            DOUBLE PRECISION NOT NULL,
    description    TEXT,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at     TIMESTAMPTZ,

    CONSTRAINT fk_tactical_markers_marker_type
        FOREIGN KEY (marker_type_id) REFERENCES tactical_marker_types (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_tactical_markers_squad
        FOREIGN KEY (squad_id) REFERENCES squads (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_tactical_markers_company
        FOREIGN KEY (company_id) REFERENCES companies (id)
        ON DELETE SET NULL,

    CONSTRAINT fk_tactical_markers_author
        FOREIGN KEY (author_id) REFERENCES users (id)
        ON DELETE SET NULL
);

CREATE INDEX idx_tactical_markers_squad_id       ON tactical_markers (squad_id);
CREATE INDEX idx_tactical_markers_company_id     ON tactical_markers (company_id);
CREATE INDEX idx_tactical_markers_marker_type_id ON tactical_markers (marker_type_id);
CREATE INDEX idx_tactical_markers_expires_at     ON tactical_markers (expires_at);
CREATE INDEX idx_tactical_markers_squad_type_expires
    ON tactical_markers (squad_id, marker_type_id, expires_at);

-- Note on "partial index for active markers":
-- Using now()/current_timestamp in an index predicate is not IMMUTABLE in PostgreSQL.
-- If you need fast queries for active markers, consider either:
--   (a) store a boolean is_active maintained by application/DB logic, or
--   (b) query with existing indexes (squad_id, marker_type_id, expires_at) and a condition expires_at IS NULL OR expires_at > :t.

-- user_geo_locations: geo history of users
CREATE TABLE user_geo_locations (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT      NOT NULL,
    lat         DOUBLE PRECISION NOT NULL,
    lng         DOUBLE PRECISION NOT NULL,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_user_geo_locations_user
        FOREIGN KEY (user_id) REFERENCES users (id)
        ON DELETE CASCADE
);

CREATE INDEX idx_user_geo_locations_user_time
    ON user_geo_locations (user_id, recorded_at DESC);

-- -----------------------
-- 3) updated_at triggers
-- -----------------------

CREATE OR REPLACE FUNCTION STN_set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_users_set_updated_at
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION STN_set_updated_at();

CREATE TRIGGER trg_companies_set_updated_at
BEFORE UPDATE ON companies
FOR EACH ROW
EXECUTE FUNCTION STN_set_updated_at();

CREATE TRIGGER trg_squads_set_updated_at
BEFORE UPDATE ON squads
FOR EACH ROW
EXECUTE FUNCTION STN_set_updated_at();

-- =====================================================================
